import * as v from 'valibot'

import { DeviceIdSchema, VaultIdSchema } from '../utils/ids'
import { NonNegativeSafeIntegerSchema, PositiveSafeIntegerSchema } from '../utils/shared'
import { ProtocolVersionSchema } from '../utils/version'

export const SetupBootstrapModeSchema = v.union([
  v.literal('new-vault'),
  v.literal('join-existing'),
])
export type SetupBootstrapMode = v.InferInput<typeof SetupBootstrapModeSchema>

const MAX_SETUP_TOKEN_LENGTH = 4096
const MAX_DEVICE_NAME_LENGTH = 128
const MAX_ACCESS_TOKEN_LENGTH = 16_384
const MAX_REFRESH_TOKEN_LENGTH = 4096

const SetupTokenSchema = v.pipe(v.string(), v.minLength(1), v.maxLength(MAX_SETUP_TOKEN_LENGTH))

export const SetupExchangeRequestSchema = v.object({
  vaultId: VaultIdSchema,
  setupToken: SetupTokenSchema,
  requestedDeviceName: v.pipe(v.string(), v.minLength(1), v.maxLength(MAX_DEVICE_NAME_LENGTH)),
  existingDeviceId: v.optional(DeviceIdSchema),
})
export type SetupExchangeRequest = v.InferInput<typeof SetupExchangeRequestSchema>

export const HttpEndpointSchema = v.pipe(
  v.string(),
  v.minLength(1),
  v.maxLength(2048),
  v.check((val) => {
    try {
      const url = new URL(val)
      return (
        (url.protocol === 'https:' || url.protocol === 'http:') &&
        url.username === '' &&
        url.password === '' &&
        url.hash === ''
      )
    } catch {
      return false
    }
  }, 'Invalid HTTP endpoint'),
)

export const SetupTokenIssueResponseSchema = v.pipe(
  v.object({
    endpoint: HttpEndpointSchema,
    vaultId: VaultIdSchema,
    setupToken: SetupTokenSchema,
    setupUri: v.pipe(v.string(), v.minLength(1), v.maxLength(4096)),
    issuedAt: NonNegativeSafeIntegerSchema,
    expiresAt: NonNegativeSafeIntegerSchema,
  }),
  v.check((val) => val.expiresAt > val.issuedAt, 'expiresAt must be after issuedAt'),
  v.check((val) => {
    try {
      const url = new URL(val.setupUri)
      return (
        url.protocol === 'kuroflare:' &&
        url.hostname === 'setup' &&
        url.searchParams.get('endpoint') === val.endpoint &&
        url.searchParams.get('vaultId') === val.vaultId &&
        url.searchParams.get('setupToken') === val.setupToken
      )
    } catch {
      return false
    }
  }, 'Invalid setup URI'),
)
export type SetupTokenIssueResponse = v.InferInput<typeof SetupTokenIssueResponseSchema>

export interface ParsedSetupUri {
  readonly endpoint: string
  readonly vaultId: string
  readonly setupToken: string
  readonly bootstrapMode?: SetupBootstrapMode | undefined
}

const SetupUriQuerySchema = v.object({
  endpoint: HttpEndpointSchema,
  vaultId: VaultIdSchema,
  setupToken: SetupTokenSchema,
  bootstrapMode: v.optional(SetupBootstrapModeSchema),
})

/**
 * Parses a `kuroflare://setup?...` URI into setup fields used by clients.
 *
 * @param setupUri URI generated by the worker setup-token issue endpoint.
 * @returns Parsed endpoint, vault ID, and setup token, or `undefined` when invalid.
 */
export function parseSetupUri(setupUri: string): ParsedSetupUri | undefined {
  try {
    const url = new URL(setupUri.trim())
    if (url.protocol !== 'kuroflare:' || url.hostname !== 'setup') {
      return undefined
    }
    const bootstrapMode = url.searchParams.get('bootstrapMode')
    const query = {
      endpoint: url.searchParams.get('endpoint'),
      vaultId: url.searchParams.get('vaultId'),
      setupToken: url.searchParams.get('setupToken'),
      ...(bootstrapMode === null
        ? {}
        : { bootstrapMode: bootstrapMode.length === 0 ? undefined : bootstrapMode }),
    }
    const result = v.safeParse(SetupUriQuerySchema, {
      ...query,
    })
    if (!result.success) {
      return undefined
    }
    return result.output
  } catch {
    return undefined
  }
}

/** Parsed fields from Obsidian's already-decoded protocol handler parameters. */
export type ParsedObsidianSetupUriParams = ParsedSetupUri

const ObsidianSetupUriParamsSchema = v.object({
  endpoint: HttpEndpointSchema,
  vaultId: VaultIdSchema,
  setupToken: SetupTokenSchema,
  bootstrapMode: v.optional(SetupBootstrapModeSchema),
})

/**
 * Validates query parameters passed to the registered Obsidian setup protocol handler.
 *
 * @param params Already-decoded parameters from Obsidian.
 * @returns Parsed setup fields, or `undefined` when validation fails.
 */
export function parseObsidianSetupUriParams(
  params: Readonly<Record<string, string | undefined>>,
): ParsedObsidianSetupUriParams | undefined {
  const result = v.safeParse(ObsidianSetupUriParamsSchema, {
    endpoint: params.endpoint,
    vaultId: params.vaultId,
    setupToken: params.setupToken,
    bootstrapMode: params.bootstrapMode === '' ? undefined : params.bootstrapMode,
  })
  return result.success ? result.output : undefined
}

export const SetupExchangeResponseSchema = v.strictObject({
  endpoint: HttpEndpointSchema,
  vaultId: VaultIdSchema,
  deviceId: DeviceIdSchema,
  accessToken: v.pipe(v.string(), v.minLength(1), v.maxLength(MAX_ACCESS_TOKEN_LENGTH)),
  refreshToken: v.pipe(v.string(), v.minLength(1), v.maxLength(MAX_REFRESH_TOKEN_LENGTH)),
  tokenVersion: PositiveSafeIntegerSchema,
  protocolVersion: ProtocolVersionSchema,
  bootstrapMode: SetupBootstrapModeSchema,
})
export type SetupExchangeResponse = v.InferInput<typeof SetupExchangeResponseSchema>
